name: clone workflow
on: 
  workflow_dispatch:   
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: ./
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port:  ${{ secrets.PORT }}
          script: |
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              git clone git@github.com:nkrishnan19/cmsc389T-web-template.git
